const STORE_API_BASE = window.STARGIRLS_STORE_API || "";
const productGrid = document.querySelector("[data-product-grid]");
const filterLinks = document.querySelectorAll("[data-shop-filter]");
const cartButtons = document.querySelectorAll("[data-cart-open]");
const cartDrawer = document.querySelector("[data-cart-drawer]");
const cartClose = document.querySelector("[data-cart-close]");
const cartBackdrop = document.querySelector("[data-cart-backdrop]");
const cartItems = document.querySelector("[data-cart-items]");
const cartCount = document.querySelectorAll("[data-cart-count]");
const cartSubtotal = document.querySelector("[data-cart-subtotal]");
const checkoutButton = document.querySelector("[data-checkout]");
const checkoutNote = document.querySelector("[data-checkout-note]");
let products = [], cart = loadCart(), activeFilter = "all";
const money = value => typeof value === "number" ? new Intl.NumberFormat("en-US", {style:"currency",currency:"USD"}).format(value) : "";
function esc(value=""){return String(value).replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));}
function safeImage(value=""){return /^(?:images\/|https:\/\/)/.test(String(value)) ? String(value).replace(/["'()\\]/g,"") : "";}
function loadCart(){try{const value=JSON.parse(localStorage.getItem("stargirls-cart"));return Array.isArray(value)?value.filter(x=>x&&typeof x.id==="string"&&Number.isFinite(x.quantity)&&x.quantity>0).map(x=>({id:x.id,size:typeof x.size==="string"?x.size:"",sku:typeof x.sku==="string"?x.sku:"",quantity:Math.min(10,Math.floor(x.quantity))})):[];}catch{return [];}}
function saveCart(){localStorage.setItem("stargirls-cart",JSON.stringify(cart));renderCart();}
const productById=id=>products.find(product=>product.id===id);
const variantFor=(product,size)=>Array.isArray(product?.variants)?product.variants.find(variant=>variant.size===size):null;
function addToCart(id,size=""){const product=productById(id);if(!product||!product.available||typeof product.price!=="number")return;const variant=Array.isArray(product.variants)?variantFor(product,size):null;if(Array.isArray(product.variants)&&!variant)return;const sku=variant?.sku||"";const existing=cart.find(item=>item.id===id&&item.size===size);if(existing)existing.quantity=Math.min(10,existing.quantity+1);else cart.push({id,size,sku,quantity:1});saveCart();openCart();}
function changeQuantity(id,size,amount){const item=cart.find(entry=>entry.id===id&&entry.size===size);if(!item)return;item.quantity=Math.min(10,item.quantity+amount);if(item.quantity<=0)cart=cart.filter(entry=>!(entry.id===id&&entry.size===size));saveCart();}
function renderProducts(){if(!productGrid)return;const visible=activeFilter==="all"?products:products.filter(product=>product.category===activeFilter);if(!visible.length){productGrid.innerHTML='<div class="catalog-empty"><strong>NOTHING HERE YET.</strong><p>Try another category.</p></div>';return;}productGrid.innerHTML=visible.map(product=>{const id=esc(product.id),name=esc(product.name),category=esc(product.category||"drop"),status=esc(product.status||"COMING SOON"),image=safeImage(product.image),hasVariants=Array.isArray(product.variants)&&product.variants.length>0;const sizePicker=hasVariants?`<label class="catalog-size-label" for="size-${id}">SIZE</label><select class="catalog-size" id="size-${id}" data-size-for="${id}" ${product.available?'':'disabled'}><option value="">SELECT SIZE</option>${product.variants.map(v=>`<option value="${esc(v.size)}">${esc(v.size)}</option>`).join("")}</select>`:"";const action=product.available&&typeof product.price==="number"?`<button class="catalog-buy" type="button" data-add-to-cart="${id}">ADD TO CART</button>`:`<span class="catalog-status">${status}</span>`;return `<article class="catalog-card" data-category="${category}"><div class="catalog-card-image" style="background-image:url(&quot;${image}&quot;)" role="img" aria-label="${name}"></div><div class="catalog-meta"><div><strong>${name}</strong><span>${category.toUpperCase()}</span></div><div class="catalog-price">${typeof product.price==="number"?money(product.price):status}</div></div>${sizePicker}${action}</article>`;}).join("");document.querySelectorAll("[data-add-to-cart]").forEach(button=>button.addEventListener("click",()=>{const id=button.dataset.addToCart;const product=productById(id);const picker=document.querySelector(`[data-size-for="${CSS.escape(id)}"]`);if(Array.isArray(product?.variants)&&!picker?.value){picker?.focus();return;}addToCart(id,picker?.value||"");}));}
function renderCart(){const hydrated=cart.map(item=>{const product=productById(item.id);const variant=Array.isArray(product?.variants)?variantFor(product,item.size):null;return {...item,product,variant};}).filter(item=>item.product&&item.product.available&&typeof item.product.price==="number"&&(!Array.isArray(item.product.variants)||item.variant));const validKeys=new Set(hydrated.map(item=>`${item.id}::${item.size}`));if(cart.some(item=>!validKeys.has(`${item.id}::${item.size}`))){cart=cart.filter(item=>validKeys.has(`${item.id}::${item.size}`));localStorage.setItem("stargirls-cart",JSON.stringify(cart));}const count=hydrated.reduce((sum,item)=>sum+item.quantity,0);cartCount.forEach(element=>element.textContent=String(count));if(!cartItems||!cartSubtotal||!checkoutButton)return;if(!hydrated.length){cartItems.innerHTML='<div class="cart-empty"><strong>YOUR CART IS EMPTY.</strong><p>The real stuff will show up here as soon as the first products go live.</p></div>';cartSubtotal.textContent=money(0);checkoutButton.disabled=true;if(checkoutNote)checkoutNote.textContent="Checkout activates when purchasable products and the payment backend are connected.";return;}cartItems.innerHTML=hydrated.map(item=>`<div class="cart-line"><div class="cart-thumb" style="background-image:url(&quot;${safeImage(item.product.image)}&quot;)"></div><div class="cart-line-copy"><strong>${esc(item.product.name)}</strong>${item.size?`<span>SIZE ${esc(item.size)}</span>`:""}<span>${money(item.product.price)}</span><div class="qty-controls"><button type="button" data-qty="-1" data-id="${esc(item.id)}" data-size="${esc(item.size)}" aria-label="Remove one">−</button><span>${item.quantity}</span><button type="button" data-qty="1" data-id="${esc(item.id)}" data-size="${esc(item.size)}" aria-label="Add one">+</button></div></div></div>`).join("");document.querySelectorAll("[data-qty]").forEach(button=>button.addEventListener("click",()=>changeQuantity(button.dataset.id,button.dataset.size||"",Number(button.dataset.qty))));cartSubtotal.textContent=money(hydrated.reduce((sum,item)=>sum+item.product.price*item.quantity,0));checkoutButton.disabled=!STORE_API_BASE;if(checkoutNote)checkoutNote.textContent=STORE_API_BASE?"Taxes and shipping are calculated at checkout.":"Cart is ready. Payment checkout will activate when the store backend is connected.";}
function openCart(){if(!cartDrawer||!cartBackdrop)return;cartDrawer.classList.add("active");cartBackdrop.classList.add("active");cartDrawer.setAttribute("aria-hidden","false");document.body.classList.add("menu-open");cartClose?.focus();}
function closeCart(){if(!cartDrawer||!cartBackdrop)return;cartDrawer.classList.remove("active");cartBackdrop.classList.remove("active");cartDrawer.setAttribute("aria-hidden","true");document.body.classList.remove("menu-open");}
async function checkout(){if(!STORE_API_BASE||!cart.length)return;checkoutButton.disabled=true;checkoutButton.textContent="OPENING CHECKOUT…";try{const response=await fetch(`${STORE_API_BASE}/checkout`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:cart})});if(!response.ok)throw new Error("Checkout request failed");const data=await response.json();if(!data.url||!/^https:\/\//.test(data.url))throw new Error("Checkout URL missing");window.location.assign(data.url);}catch(error){console.error("STARGIRLS checkout:",error);checkoutButton.disabled=false;checkoutButton.textContent="CHECKOUT";if(checkoutNote)checkoutNote.textContent="Checkout could not open. Please try again.";}}
async function initStore(){try{const response=await fetch("content/products.json",{cache:"no-store"});if(!response.ok)throw new Error("Could not load products");const data=await response.json();products=Array.isArray(data.products)?data.products:[];}catch(error){console.error("STARGIRLS products:",error);products=[];}renderProducts();renderCart();}
filterLinks.forEach(link=>link.addEventListener("click",event=>{event.preventDefault();activeFilter=link.dataset.shopFilter||"all";filterLinks.forEach(item=>item.classList.toggle("active",item.dataset.shopFilter===activeFilter));renderProducts();document.querySelector("#catalog")?.scrollIntoView({behavior:"smooth",block:"start"});}));
cartButtons.forEach(button=>button.addEventListener("click",openCart));cartClose?.addEventListener("click",closeCart);cartBackdrop?.addEventListener("click",closeCart);checkoutButton?.addEventListener("click",checkout);document.addEventListener("keydown",event=>{if(event.key==="Escape")closeCart();});initStore();
